#' @importFrom methods as new slot slot<- validObject
NULL

#' S4 class to represent a pedigree.
#'
#' A pedigree is a ensemble of individuals linked to each other into
#' a family tree.
#'
#' They are created from a data.frame containing the individuals informations
#' and a relation ship data.frame for the special links between individuals.
#' A list of scales can be provided to create a legend.
#' To create a Pedigree object, use the function
#' [Pedigree()].
#'
#' @slot ped A data.frame with the individuals informations. The minimum
#' columns required are 'id', 'dadid', 'momid' and 'sex'. Other columns can be
#' added to the data.frame and will be recognised by the functions. Some
#' errors can be detected by the validity function and some of them can be
#' corrected and others will be added to a dedicated column.
#' @slot rel A data.frame for the special relationship between
#' individuals.
#' The minimum columns required are 'id1', 'id2' and 'code'.
#' @slot scales A data.frame to use for the affection status.
#' This data.frame is generated by the function
#' [generate_aff_inds()] followed by
#' [generate_colors()].
#' @slot hints List of two elements.
#' - **order** is a numeric vector with one element per subject in the
#' Pedigree.  It determines the relative order of subjects within a sibship, as
#' well as the relative order of processing for the founder couples. (For this
#' latter, the female founders are ordered as though they were sisters).
#' - **spouse** is a matrix with one row per hinted marriage, usually
#' only a few marriages in a Pedigree will need an added hint, for
#' instance reverse the plot order of a husband/wife pair.
#' Each row contains the index of the left spouse, the right hand spouse,
#' and the anchor (i.e : `1` = left, `2` = right, `0` = either).
#'
#' @return A Pedigree object.
#' @seealso [Pedigree()]
#' @docType class
#' @name Pedigree-class
#' @rdname Pedigree-class
#' @aliases Pedigree-class
#' @include validity.R
#' @include Pedigree.R
#' @export
setClass(
    "Pedigree",
    slots = c(
        ped = "data.frame",
        rel = "data.frame",
        scales = "list",
        hints = "list"
    )
)

setValidity("Pedigree", is_valid)

#### S4 Accessors ####

#' @title Pedigree ped accessors
#' @param object A Pedigree object.
#' @return The slot `ped` present in the Pedigree object.
#' @rdname extract-methods
#' @aliases ped,Pedigree-method
#' @export
setGeneric("ped", function(object) {
    standardGeneric("ped")
})

setMethod("ped", signature(object = "Pedigree"), function(object) {
    object@ped
})

setGeneric("ped<-", function(object, value) {
    standardGeneric("ped<-")
})

setMethod(
    "ped<-",
    signature(object = "Pedigree", value = "ANY"),
    function(object, value) {
        object@ped <- value
        validObject(object)
        object
    }
)

#' @description Pedigree rel accessors
#' @param object A Pedigree object.
#' @return The slot `rel` present in the Pedigree object.
#' @rdname extract-methods
#' @aliases rel,Pedigree-method
#' @export
setGeneric("rel", function(object) {
    standardGeneric("rel")
})

setMethod("rel", signature(object = "Pedigree"), function(object) {
    object@rel
})

setGeneric("rel<-", function(object, value) {
    standardGeneric("rel<-")
})

setMethod(
    "rel<-",
    signature(object = "Pedigree", value = "ANY"),
    function(object, value) {
        object@rel <- value
        validObject(object)
        object
    }
)

#' @description Pedigree scales accessors
#' @param object A Pedigree object.
#' @return The slot `scales` present in the Pedigree object.
#' @rdname extract-methods
#' @aliases scales,Pedigree-method
#' @export
setGeneric("scales", function(object) {
    standardGeneric("scales")
})

setMethod("scales", signature(object = "Pedigree"), function(object) {
    object@scales
})

setGeneric("scales<-", function(object, value) {
    standardGeneric("scales<-")
})

setMethod(
    "scales<-",
    signature(object = "Pedigree", value = "ANY"),
    function(object, value) {
        object@scales <- value
        validObject(object)
        object
    }
)

#' @description Pedigree hints accessors
#' @param object A Pedigree object.
#' @return The slot `hints` present in the Pedigree object.
#' @rdname extract-methods
#' @aliases hints,Pedigree-method
#' @export
setGeneric("hints", function(object) {
    standardGeneric("hints")
})

setMethod("hints", signature(object = "Pedigree"), function(object) {
    object@hints
})

setGeneric("hints<-", function(object, value) {
    standardGeneric("hints<-")
})

setMethod(
    "hints<-",
    signature(object = "Pedigree", value = "ANY"),
    function(object, value) {
        object@hints <- value
        validObject(object)
        object
    }
)


#' @description Pedigree hints accessors
#' @param object A Pedigree object.
#' @return The slot `hints` present in the Pedigree object.
#' @rdname extract-methods
#' @aliases hints,Pedigree-method
#' @export
setGeneric("col_id", function(object, col) {
    standardGeneric("col_id")
})

setMethod(
    "col_id",
    signature(object = "Pedigree", col = "ANY"),
    function(object, col) {
        col_id <- c("id", "dadid", "momid", "sex")
        if (is.null(col)) {
            col <- col_id
        } else if (!all(col %in% col_id)) {
            stop(
                "Col selected: ",
                col[!col %in% col_id],
                " is not an identity column"
            )
        }
        ped(ped)[col]
    }
)

setGeneric("col_id<-", function(object, value) {
    standardGeneric("col_id<-")
})

setMethod(
    "col_id<-",
    signature(object = "Pedigree", col = "ANY", value = "ANY"),
    function(object, value) {
        if (! length(value) %in% c(1, length(object))) {
            stop(
                "The length of the new value should be:",
                "1 or equal to the length of the pedigree"
            )
        }
        ped(ped)[col] <- value
        validObject(object)
        object
    }
)

#### S4 methods ####

#' @title Pedigree methods
#' @description Pedigree show method
#' @param object A Pedigree object.
#' @return A character vector with the informations about the object.
#' @rdname extract-methods
#' @aliases show,Pedigree-method
setMethod("show", signature(object = "Pedigree"), function(object) {
    nb_fam <- length(levels(as.factor(object@ped$family)))
    cat("Pedigree object with", nrow(object@ped), "individuals and",
        nrow(object@rel), "special relationships across", nb_fam, "families",
        fill = TRUE)
})

#' @description Pedigree summary method.
#' @param object A Pedigree object.
#' @return A character vector with the summary of the object.
#' @rdname extract-methods
#' @aliases summary,Pedigree-method
setMethod("summary", signature(object = "Pedigree"), function(object) {
    cat("Pedigree object with", nrow(object@ped), "individuals", fill = TRUE)
    print(summary(object@ped, maxsum = 5))
    cat("and", nrow(object@rel), "special relationships.", fill = TRUE)
    print(summary(object@rel))
    cat("The filling scales columns are:",
        levels(as.factor(object@scales$fill$column_values)), fill = TRUE
    )
    cat("The border scale column are:",
        levels(as.factor(object@scales$border$column)), fill = TRUE
    )
})

#' @description Extract parts of a Pedigree object
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @param ... Other arguments.
#' @rdname extract-methods
#' @return The slot `i` present in the Pedigree object.
setMethod("[[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, ..., drop = TRUE) {
        slot(x, i)
    }
)

#' @description Extract parts of a Pedigree object
#' @param x A Pedigree object.
#' @param name A slot name.
#' @rdname extract-methods
#' @return The slot `name` present in the Pedigree object.
#'
setMethod("$", c(x = "Pedigree"),
    function(x, name) {
        slot(x, name)
    }
)

#' @description Replace parts of a Pedigree object
#' @param x A Pedigree object.
#' @param name A slot name.
#' @param value A vector of values to replace.
#' @rdname extract-methods
#' @return The Pedigree object with the slot `name` replaced by `value`.
setMethod("$<-", c(x = "Pedigree"),
    function(x, name, value) {
        slot(x, name) <- value
        validObject(x)
        x
    }
)

#' @description Subset the hints list based on the index given
#' @param hints A list of hints
#' @param index A vector of index
#' @return A list of hints subsetted
#' @rdname extract-methods
#' @aliases sub_sel_hints,Pedigree-method
#' @keywords internal
sub_sel_hints <- function(hints, index) {
    if (!is.null(hints$order)) {
        temp <- list(order = hints$order[index])
    } else {
        temp <- list(order = NULL)
    }

    if (!is.null(hints$spouse)) {
        indx1 <- match(hints$spouse[, 1], index, nomatch = 0)
        indx2 <- match(hints$spouse[, 2], index, nomatch = 0)
        keep <- (indx1 > 0 & indx2 > 0)  # keep only if both id's are kept
        if (any(keep)) {
            temp$spouse <- cbind(indx1[keep], indx2[keep],
                hints$spouse[keep, 3]
            )
        }
    } else {
        temp$spouse <- NULL
    }
    temp
}

#' @description Extract parts of a Pedigree object
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @rdname extract-methods
#' @return A Pedigree object subsetted.
setMethod("[", c(x = "Pedigree", i = "ANY", j = "ANY"),
    function(x, i, j, drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i, j, drop = drop]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId | x$rel$id2 %in% allId, ]
        idx <- match(allId, ped_df$id, nomatch = 0)
        sub_hints <- sub_sel_hints(x$hints, idx)
        fill <- x$scales$fill[x$scales$fill$column_values %in% names(ped_df),]
        border <- x$scales$border[x$scales$border$column %in% names(ped_df),]
        scales <- list(fill = fill, border = border)

        new_ped <- Pedigree(ped_df, rel_df, scales,
            hints = sub_hints, cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' @description Extract parts of a Pedigree object
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @return A Pedigree object subsetted.
#' @rdname extract-methods
setMethod("[", c(x = "Pedigree", i = "missing", j = "ANY"),
    function(x, i, j, drop = TRUE) {
        ped_df <- x$ped[, j, drop = drop]
        new_ped <- Pedigree(ped_df, x$rel, x$scales,
            cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' @description Extract parts of a Pedigree object
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @return A Pedigree object subsetted.
#' @rdname extract-methods
setMethod("[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i, ]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId & x$rel$id2 %in% allId, ]
        idx <- match(allId, ped_df$id, nomatch = 0)
        sub_hints <- sub_sel_hints(x$hints, idx)
        new_ped <- Pedigree(ped_df, rel_df, x$scales,
            hints = sub_hints, cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' Convert a Pedigree object to a data.frame
#' @param x A Pedigree object.
#' @return A data.frame with the individuals informations.
#' @docType methods
#' @aliases as.data.frame,Pedigree-method
#' @export
setMethod("as.data.frame", c(x = "Pedigree"),
    function(x) {
        x$ped
    }
)

#' Convert a Pedigree object to a list
#' @param x A Pedigree object.
#' @return A list with all the slots of the Pedigree object.
#' @docType methods
#' @aliases as.list,Pedigree-method
#' @export
setMethod("as.list", c(x = "Pedigree"),
    function(x) {
        list(
            ped = x$ped,
            rel = x$rel,
            scales = x$scales,
            hints = x$hints
        )
    }
)

#' Compute the length of a Pedigree object
#' @param x A Pedigree object.
#' @return The number of individuals in the Pedigree object.
#' @docType methods
#' @aliases length,Pedigree-method
#' @export
setMethod("length", c(x = "Pedigree"),
    function(x) {
        nrow(x$ped)
    }
)