#' @importFrom methods as new slot slot<- validObject
NULL

#' S4 class to represent a pedigree.
#'
#' A pedigree is a ensemble of individuals linked to each other into
#' a family tree.
#'
#' They are created from a data.frame containing the individuals informations
#' and a relation ship data.frame for the special links between individuals.
#' A list of scales can be provided to create a legend.
#' To create a Pedigree object, use the function [pedigree()].
#'
#' @slot ped A data.frame with the individuals informations. The minimum
#' columns required are 'id', 'dadid', 'momid' and 'sex'. Other columns can be
#' added to the data.frame and will be recognised by the functions. Some
#' errors can be detected by the validity function and some of them can be
#' corrected and others will be added to a dedicated column.
#' @slot rel A data.frame for the special relationship between individuals.
#' The minimum columns required are 'id1', 'id2' and 'code'.
#' @slot scales A data.frame to use for the affection status. This data.frame
#' is generated by the function [generate_aff_inds()] followed by
#' [generate_colors()].
#' @slot hints List of two elements.
#' - **order** is a numeric vector with one element per subject in the
#' pedigree.  It determines the relative order of subjects within a sibship, as
#' well as the relative order of processing for the founder couples. (For this
#' latter, the female founders are ordered as though they were sisters).
#' - **spouse** is a matrix with one row per hinted marriage, usually only
#' a few marriages in a pedigree will need an added hint, for instance reverse
#' the plot order of a husband/wife pair. Each row contains the index of the
#' left spouse, the right hand spouse, and the anchor
#' (i.e : `1` = left, `2` = right, `0` = either).
#' @seealso [pedigree()]
#' @docType class
#' @name Pedigree-class
#' @rdname Pedigree-class
#' @aliases Pedigree-class
#' @include validity.R
#' @include pedigree.R
#' @export
setClass(
    "Pedigree",
    slots = c(
        ped = "data.frame",
        rel = "data.frame",
        scales = "list",
        hints = "list"
    )
)

setValidity("Pedigree", is_valid)

#### S4 methods ####

#' Pedigree show method.
#' @param object A Pedigree object.
#' @return A character vector with the informations about the object.
#' @rdname extract-methods
#' @aliases show,Pedigree-method
setMethod("show", signature(object = "Pedigree"), function(object) {
    nb_fam <- length(levels(as.factor(object@ped$family)))
    cat("Pedigree object with", nrow(object@ped), "individuals and",
        nrow(object@rel), "special relationships across", nb_fam, "families",
        fill = TRUE)
})

#' Pedigree summary method.
#' @param object A Pedigree object.
#' @return A character vector with the summary of the object.
#' @rdname extract-methods
#' @aliases summary,Pedigree-method
setMethod("summary", signature(object = "Pedigree"), function(object) {
    cat("Pedigree object with", nrow(object@ped), "individuals", fill = TRUE)
    print(summary(object@ped, maxsum = 5))
    cat("and", nrow(object@rel), "special relationships.", fill = TRUE)
    print(summary(object@rel))
    cat("The filling scales columns are:", levels(as.factor(object@scales$fill$column_values)), fill = TRUE)
    cat("The border scale column are:", levels(as.factor(object@scales$border$column)), fill = TRUE)
})

#' Extract parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @param ... Other arguments.
#' @return The slot `i` present in the pedigree object.
setMethod("[[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, ..., drop = TRUE) {
        slot(x, i)
    }
)

#' Replace parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param value A vector of values to replace.
#' @param ... Other arguments.
#' @return The pedigree object with the slot `i` replaced by `value`.
setMethod("[[<-", c(x = "Pedigree", i = "ANY", j = "missing", value = "ANY"),
    function(x, i, j, ..., value) {
        slot(x, i) <- value
        validObject(x)
        x
    }
)

#' Extract parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param name A slot name.
#' @return The slot `name` present in the pedigree object.
#'
setMethod("$", c(x = "Pedigree"),
    function(x, name) {
        slot(x, name)
    }
)

#' Replace parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param name A slot name.
#' @param value A vector of values to replace.
#' @return The pedigree object with the slot `name` replaced by `value`.
setMethod("$<-", c(x = "Pedigree"),
    function(x, name, value) {
        slot(x, name) <- value
        validObject(x)
        x
    }
)

#' Subset the hints list based on the index given
#'
#' @param hints A list of hints
#' @param index A vector of index
#' @return A list of hints subsetted
#' @rdname extract-methods
#' @aliases sub_sel_hints,Pedigree-method
#' @keywords internal
sub_sel_hints <- function(hints, index) {
    if (!is.null(hints$order)) {
        temp <- list(order = hints$order[index])
    } else {
        temp <- list(order = NULL)
    }

    if (!is.null(hints$spouse)) {
        indx1 <- match(hints$spouse[, 1], index, nomatch = 0)
        indx2 <- match(hints$spouse[, 2], index, nomatch = 0)
        keep <- (indx1 > 0 & indx2 > 0)  # keep only if both id's are kept
        if (any(keep)) {
            temp$spouse <- cbind(indx1[keep], indx2[keep],
                hints$spouse[keep, 3]
            )
        }
    } else {
        temp$spouse <- NULL
    }
    temp
}

#' Extract parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @return A Pedigree object subsetted.
setMethod("[", c(x = "Pedigree", i = "ANY", j = "ANY"),
    function(x, i, j, drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i, j, drop = drop]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId | x$rel$id2 %in% allId, ]
        idx <- match(allId, ped_df$id, nomatch = 0)
        sub_hints <- sub_sel_hints(x$hints, idx)
        fill <- x$scales$fill[x$scales$fill$column_values %in% names(ped_df),]
        border <- x$scales$border[x$scales$border$column %in% names(ped_df),]
        scales <- list(fill = fill, border = border)

        new_ped <- pedigree(ped_df, rel_df, scales,
            hints = sub_hints, cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' Extract parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @return A Pedigree object subsetted.
setMethod("[", c(x = "Pedigree", i = "missing", j = "ANY"),
    function(x, i, j, drop = TRUE) {
        ped_df <- x$ped[, j, drop = drop]
        new_ped <- pedigree(ped_df, x$rel, x$scales,
            cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' Extract parts of a Pedigree object
#'
#' @param x A Pedigree object.
#' @param i A vector of individuals id or a vector of index.
#' @param j A vector of columns names.
#' @param drop A logical value indicating if the dimensions should be dropped.
#' @return A Pedigree object subsetted.
setMethod("[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i,]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId & x$rel$id2 %in% allId, ]
        idx <- match(allId, ped_df$id, nomatch = 0)
        sub_hints <- sub_sel_hints(x$hints, idx)
        new_ped <- pedigree(ped_df, rel_df, x$scales,
            hints = sub_hints, cols_ren_ped = NULL, normalize = FALSE
        )
        validObject(new_ped)
        new_ped
    }
)

#' Convert a Pedigree object to a data.frame
#'
#' @param x A Pedigree object.
#' @return A data.frame with the individuals informations.
#' @docType methods
#' @aliases as.data.frame,Pedigree-method
#' @export
setMethod("as.data.frame", c(x = "Pedigree"),
    function(x) {
        x$ped
    }
)

#' Convert a Pedigree object to a list
#' @param x A Pedigree object.
#' @return A list with all the slots of the pedigree object.
#' @docType methods
#' @aliases as.list,Pedigree-method
#' @export
setMethod("as.list", c(x = "Pedigree"),
    function(x) {
        list(
            ped = x$ped,
            rel = x$rel,
            scales = x$scales,
            hints = x$hints
        )
    }
)