# S4 Pedigree classe ###

#' @include validity.R
#' @include pedigree.R
#' A class to represent a pedigree.
#'
#' A pedigree is a ensemble of individuals linked to each other into
#' a family tree.
#'
#' They are created from a data.frame containing the individuals informations
#' and a relation ship data.frame for the special links between individuals.
#' A list of scales can be provided to create a legend.
#' To create a Pedigree object, use the function \code{pedigree}.
#'
#' @slot ped A data.frame with the individuals informations. The minimum
#' columns required are 'id', 'dadid', 'momid' and 'sex'. Other columns can be
#' added to the data.frame and will be recognised by the functions. Some
#' errors can be detected by the validity function and some of them can be
#' corrected and others will be added to a dedicated column.
#' @slot rel A data.frame for the special relationship between individuals.
#' The minimum columns required are 'id1', 'id2' and 'code'.
#' @slot scales A data.frame to use for the affection status. This data.frame
#' is generated by the function \code{generate_aff_inds} followed by
#' \code{generate_colors}.
#' @seealso \\link{pedigree}
#' @exportClass Pedigree
setClass(
    "Pedigree",
    slots = c(
        ped = "data.frame",
        rel = "data.frame",
        scales = "list"
    )
)

setValidity("Pedigree", isValid)

#### S4 methods ####

#' Pedigree show method.
#' @param object A Pedigree object.
#' @return A character vector with the informations about the object.
setMethod("show", signature(object = "Pedigree"), function(object) {
    nb_fam <- length(levels(as.factor(object@ped$family)))
    cat("Pedigree object with", nrow(object@ped), "individuals and",
        nrow(object@rel), "special relationships across", nb_fam, "families",
        fill = TRUE)
})

#' Pedigree summary method.
#' @param object A Pedigree object.
#' @return A character vector with the summary of the object.
setMethod("summary", signature(object = "Pedigree"), function(object) {
    cat("Pedigree object with", nrow(object@ped), "individuals", fill = TRUE)
    cols_summary <- c("family", "id", "dadid", "momid", "sex", "avail")
    print(summary(object@ped[cols_summary], maxsum = 5))
    cat("and", nrow(object@rel), "special relationships.", fill = TRUE)
    print(summary(object@rel))
    cat("The scales are:", levels(as.factor(object@scales$column)), fill = TRUE)
})

setMethod("[[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, ..., drop = TRUE) {
        slot(x, i)
})

setMethod("[[<-", c(x = "Pedigree", i = "ANY", j = "missing", value = "ANY"),
    function(x, i, j, ..., value) {
        slot(x, i) <- value
        validObject(x)
        x
})

setMethod("$", c(x = "Pedigree"),
    function(x, name) {
        slot(x, name)
})

setMethod("$<-", c(x = "Pedigree"),
    function(x, name, value) {
        slot(x, name) <- value
        validObject(x)
        x
})

setMethod("[", c(x = "Pedigree", i = "ANY", j = "ANY"),
    function(x, i, j, ..., drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i, j, drop = drop]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId | x$rel$id2 %in% allId, ]
        new_ped <- pedigree(ped_df, rel_df, x$scales, cols_ren_ped = NULL, normalize = FALSE)
        validObject(new_ped)
        new_ped
})

setMethod("[", c(x = "Pedigree", i = "missing", j = "ANY"),
    function(x, i, j, ..., drop = TRUE) {
        ped_df <- x$ped[, j, drop = drop]
        new_ped <- pedigree(ped_df, x$rel, x$scales, cols_ren_ped = NULL, normalize = FALSE)
        validObject(new_ped)
        new_ped
})

setMethod("[", c(x = "Pedigree", i = "ANY", j = "missing"),
    function(x, i, j, ..., drop = TRUE) {
        if (is.factor(i)) {
            i <- as.character(i)
        }
        if (is.character(i)) {
            i <- which(x$ped$id %in% i)
        }
        ped_df <- x$ped[i,]
        allId <- unique(c(ped_df$id, ped_df$dadid, ped_df$momid))
        rel_df <- x$rel[x$rel$id1 %in% allId | x$rel$id2 %in% allId, ]
        new_ped <- pedigree(ped_df, rel_df, x$scales, cols_ren_ped = NULL, normalize = FALSE)
        validObject(new_ped)
        new_ped
})

setMethod("as.data.frame", c(x = "Pedigree"), 
    function(x, ...) {
        x$ped
    }
)

setMethod("as.list", c(x = "Pedigree"), 
    function(x, ...) {
        list(
            ped = x$ped,
            rel = x$rel,
            scales = x$scales
        )
    }
)